### ISSUE TITLE
SoftwareSystemInstance definition should have softwareSystemId, not containerId

### ISSUE THREAD

**Issue by yt-ms** [structurizr/json#1]
Currently in [structurizr.yaml](https://github.com/structurizr/json/blob/master/structurizr.yaml), `SoftwareSystemInstance` is defined (line 421 onwards) as:
```yaml
SoftwareSystemInstance:
      type: object
      description: An instance of a software system, running on a deployment node.
      properties:
        id:
          type: string
          description: The ID of this software system instance in the model.
        containerId:
          type: string
          description: The ID of the software system this is an instance of.
        instanceId:
          type: number
          description: The number/index of this instance.
        ....
```

I would have thought that the `containerId` property should actually be `softwareSystemId`.
